name: Auto Build arm64

on:
  push:
#    branches:
#      - master
    tags:
      - '*'
#  pull_request:
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Clone source
      run: |
        curl -L "https://github.com/gh-tt/cloudflare-scanner/releases/download/v1.2.0/cloudflare-scanner_1.2.0_linux_arm64.tar.gz" | tar -zx

    - name: build and push image
      uses: docker/build-push-action@v2

      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: artxia/cf-scanner-docker
        platforms: linux/arm64
        target: latest-arm64
