name: Auto Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
#  pull_request:
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Clone source
      run: |
        curl -L "https://github.com/gh-tt/cloudflare-scanner/releases/download/v1.2.0/cloudflare-scanner_1.2.0_linux_64-bit.tar.gz" | tar -zx

    - name: build and push image
      uses: docker/build-push-action@v1

      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: artxia/cf-scanner-docker
        tag_with_ref: true
        add_git_labels: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
