name: Auto Build

on:
  push:
#    branches:
#      - master
    tags:
      - '*'
#  pull_request:
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Clone source
      run: |
        echo 'OVERLAY_VERSION<<EOF' >> $GITHUB_ENV
        curl -sX GET "https://api.github.com/repos/gh-tt/cloudflare-scanner/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]'$GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        curl -L "https://github.com/gh-tt/cloudflare-scanner/releases/download/${OVERLAY_VERSION}/cloudflare-scanner_${OVERLAY_VERSION#v}_linux_64-bit.tar.gz" | tar -zx

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          artxia/cf-scanner-docker:latest
          artxia/cf-scanner-docker:${OVERLAY_VERSION}
