name: Auto Build

on:
  push:
#    branches:
#      - master
    tags:
      - '*'
#  pull_request:
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Clone source
      run: |
        OVERLAY_VERSION=$(curl -sX GET "https://api.github.com/repos/gh-tt/cloudflare-scanner/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')
        curl -L "https://github.com/gh-tt/cloudflare-scanner/releases/download/${OVERLAY_VERSION}/cloudflare-scanner_${OVERLAY_VERSION#v}_linux_64-bit.tar.gz" | tar -zx
        echo "OVERLAY_VERSION=${OVERLAY_VERSION}" >> $GITHUB_ENV

    - name: build and push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: artxia/cf-scanner-docker
        tags: latest,${{ env.OVERLAY_VERSION }}
